Repository mattermost/matterwick, pull requests merged in 2020-08, with the labels that each got.

#9 [MM-26940] Matterwick support for CWS
  .gitignore
  Dockerfile
  README.md
  config/config-matterwick.default.json
  go.mod
  go.sum
  server/config.go
  server/kubernetes.go
  server/pull_request.go
  server/server.go
  server/spinwick.go
  templates/cws/cws_deployment.tmpl
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note

#10 fix location when saving the template file
  config/config-matterwick.default.json
  server/spinwick.go
Labels: 4: Reviews Complete, kind/bug, release-note

#11 Add feeback when the upgrade is done
  Dockerfile
  Makefile
  server/kubernetes.go
  server/spinwick.go
Labels: kind/cleanup, release-note

#12 add PR number when createing PV because this resource is cluster scope
  server/kubernetes.go
  server/spinwick.go
  templates/cws/cws_deployment.tmpl
Labels: kind/bug, release-note

#13 delete namespace but first delete all resources inside
  server/kubernetes.go
  server/pull_request.go
  server/spinwick.go
Labels: 4: Reviews Complete, kind/cleanup, release-note

#14 MM-27719: use multitenant rds as datastore and s3 as filestore
  go.mod
  go.sum
  main.go
  server/spinwick.go
Labels: kind/feature, release-note

#15 cws: change the order to have the secrets created first and add new env var
  config/config-matterwick.default.json
  server/config.go
  templates/cws/cws_deployment.tmpl
Labels: release-note-none

#16 add new env called CWS_CLOUD_DNS_DOMAIN
  config/config-matterwick.default.json
  server/config.go
  templates/cws/cws_deployment.tmpl
Labels: 2: Dev Review, release-note-none

#17 Add new environment variables for CWS license generation
  config/config-matterwick.default.json
  server/config.go
  templates/cws/cws_deployment.tmpl
Labels: release-note

#18 Correct incorrect variable names from PR #17
  config/config-matterwick.default.json
Labels: release-note-none
