Repository mattermost/matterwick, pull requests merged in 2023-11, with the labels that each got.

#61 Update docker repositories
  server/spinwick.go
Labels: 2: Dev Review, release-note

#62 Fix a potential panic in Matterwick log of installation ID
  server/spinwick.go
Labels: 2: Dev Review, release-note-none

#63 Fix last potential panic location
  server/spinwick.go
Labels: 4: Reviews Complete, release-note-none
