Repository mattermost/matterwick, pull requests merged in 2025-02, with the labels that each got.

#70 remove unused function messageByUserContains()
  server/server.go
Labels: release-note-none

#69 [MM-62271] Implement `/spinwick` slash command
  .gitignore
  internal/cloudtools/installation.go
  internal/cws/client.go
  server/builds.go
  server/github.go
  server/pull_request.go
  server/server.go
  server/slash_commands.go
  server/slash_commands_test.go
  server/spinwick.go
  server/utils.go
  server/utils_test.go
  server/webhook.go
Labels: 4: Reviews Complete, release-note

#72 Fix backwards compatibility with non oauth enabled provisioner
  model/cloud_client.go
  server/server.go
Labels: 2: Dev Review, release-note-none
